#!/usr/bin/expect


proc detect_vendor {} {}

proc initvars {} {
	uplevel {
		set prompt "(%|#|\\\$|>) *$"
		set send_human {.1 .3 1 .05 2}
		set send_slow {2 .001}
		# specific to this piece
		set vendor_detected 0
		set device_vendor "unknown"
		log_user 0 
	}
}

proc login_to_device {hostname user password} {

	global login_success prompt

	if {[catch {spawn ssh $user@$hostname} err ]} {
		puts stderr "ERROR: Failed to login to device\nError: $err" 
		return 1;
	} 
# We will leave the session open for further functions to interact
	uplevel set spawn_id $spawn_id 
	set login_success 1

	expect {
		-re "assword:.*$" {
			send "$password\r" ;
			exp_continue ;
		}
		-re $prompt { }
	}
	return 0;
}

proc init_terminal {} {
	global prompt
	send -h "\r" ;
	expect {
		-re $prompt {
			send "set cli screen-length 0\r" ;
		}
	}
	return 0;
}

proc detect_vendor {} {

	global vendor_detected device_vendor prompt device_vendor

	send -s  "\r" ;
	expect {
		-re $prompt {
			if {$vendor_detected == 0} {
				send "show version\r" ;
				expect {
					-re "(ptx1000|JUNOS)" {
						set device_vendor "juniper"
						expect -re $prompt {}
					}
					-re "(Nokia)" {
						set device_vendor "nokia"
						expect -re $prompt {}
					}
					-re "\(more\)" {
						send -s  "\r" ;
						exp_continue ;
					}

				}
				incr vendor_detected 1 
			}
		}
	}
	return $device_vendor 
}


initvars ;
login_to_device "100.80.15.102" "rancid" "level3" ;
puts [detect_vendor]
