

proc myproc {} {
	puts "This is from global myproc"
}

proc myproc2 {} { 
	puts "stub for myproc2" 
}

namespace eval Nokia {
	namespace export myproc myproc2 ;
	variable arp_entry "nokia" ;

	proc myproc {} {
		set v value2Nokia
		puts "This is from Namespace [namespace current] myproc. having v = $v" ;
	}

	proc myproc2 {} {
		variable arp_entry

		puts "This arp_entry is $arp_entry" ;
	}

}

namespace eval Juniper {
	namespace export myproc myproc2 ;
	variable arp_entry "juniper"

	proc myproc {} {
		set v value2Junos
		puts "This is from Namespace [namespace current] myproc. having v = $v" ;
	}

	proc myproc2 {} {
		variable arp_entry

		puts "This arp_entry is $arp_entry" ;
	}

}

puts [myproc]

set ns {::Juniper}
set context [append {::} $ns {::*}]

namespace import -force $context 

puts [myproc]

puts [myproc2]
