

exp_internal 0
log_user 0

#strace 10 

source ./util.exp

set DEBUG Y


set emailid {muralikrishnan.s@gmail.com}

#puts [regexp -about {^(.*)@(.*)\.(.*)$} $emailid]
#if { [regexp  {^(\[^@]*)@(\[.]*)\.(\[^\r]*)$} $emailid] } {

if {[regexp  {^([^@]*)@(\w+)\.(\w+)$} $emailid email username subdomain domain] } {
	puts "found a match" 
} else { 
	puts "no regexp match"
}

if {[regsub  {^([^@]*)@(\w+)\.(\w+)$} $emailid {\2@\1.\3} newemail] } {
	puts "replacement done"
} else { 
	puts "No match. no replacement happend" ;
}
#regexp "^(\[^@]+)@(\[.]+)\.(\[^\r]+)$" $emailid # email username subdomain domain

!# emailid email username subdomain domain newemail
