

## Simple proc to debug and list provided variables and values at that point in time
## Source: https://wiki.tcl-lang.org/page/What+debugging+tools+are+available+to+a+Tcl+programmer
set DEBUG 0

proc !# {args} {
    global DEBUG
    #if {$DEBUG == 1 || $DEBUG == TRUE || $DEBUG == true || $DEBUG == yes || $DEBUG == on || $DEBUG == ON} {}
    if { [string is true $DEBUG] } {
        set res [list]
        foreach i $args {
             if [uplevel info exists $i] {
                 lappend res "$i=[uplevel set $i]"
             } else {
                 lappend res $i
             }
        }
        puts stderr $res
    }
}

proc debug_on {} {
	global debug_enable
	if {$debug_enable} {exp_internal 1}
}

proc debug_off {} {
	exp_internal 0
}
