#!/usr/bin/expect --

#log_user 1 ;
exp_internal 1

source ./util.exp

#set spid [spawn ssh msolayap@dc2owooadmpd01.it.savvis.net]
spawn ssh msolayap@dc2-owras04.mgmt.savvis.net

#puts "Spawn ID: $spid" ;

set DEBUG 0;
set prompt {.*?\]\$*} ;
set first_prompt 0
set auth_done 0 
set passwd "svvs123!" ;

expect {
	-glob "(yes/no)*" {
		send  "yes\r" ;
		exp_continue ;
	}
	-glob "assword:*"  { 
		if { $auth_done == 0 } {
			send "$passwd\r" ;
			incr auth_done 1
		} else {
			send_user "Auth failed 1 time. could be wrong password\r" ;
			exit 1 ;
		}
	} 
	eof  { 
		send_user "password prompt not appeared. exiting" ;
		exit 1;
	}
	timeout  {
		send_user "password prompt timed out. exiting" ;
		exit 1 ;
	}
}


if { $auth_done < 1 } {
	send_user "something went wront. Auth not completed yet. exiting" ;
	exit 1;
}

set this_hostname [exec hostname] ;

send "\r" ;  # A pseudo enter to make prompt to reappear.

set timeout 120 ;
expect {

	-glob $prompt  { 
		if { $first_prompt == 0 } {
			send "ping -c3 $this_hostname\r" 
			incr first_prompt 1
			expect {
				-glob "ping statistics" {
					sleep 1;
				}
				-glob "unknown host" { 
					send_user "ping failed" ;
				}
				eof 
				timeout 
			}
		} else { 
			puts $expect_out(buffer);
			send "exit\r\n" ;
		}
	}
	eof { 
		puts stderr "EOF occured while waiting in expect block" ;
		exit 1;
	}
	timeout { puts stderr "Script timed out" }
}

!# prompt  first_prompt auth_done 
